/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoApp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Tasks;
import util.ConnectionFactory;



public class App {
    public static void main(String[] args) {
    
    }
}
